project:
  type: website
  output-dir: docs
  
lang: es
website:
  site-url: https://joel-x.github.io/jb_blog/
  title: Joel Burbano
  description: Portafolio Joel Burbano
  navbar:
    left: 
      - about.qmd
      - blog.qmd
      - proyects.qmd
    right:
      - icon: github
        href: https://github.com/joel-x
      - icon: whatsapp
        href: https://wa.me/593997868351
      - icon: linkedin
        href: https://www.linkedin.com/in/jxbsjb
      - icon: envelope
        href: mailto:joelburbano@outlook.com
  search:
    location: navbar
    type: textbox
format:
  html:
    #max-width: fit content(25em)
    theme:
      dark: darkly
      light: flatly
      
    linestretch: 1.7
    css: styles.css

editor: visual

