project:
  type: website
  output-dir: docs
  


website:
  google-analytics: "G-C1J6R1KB4G"
  site-url: https://joel-x.github.io/jb_blog/
  title: Joel Burbano
  description: Portafolio Joel Burbano
  
  navbar:
    left: 
      #- about.qmd
      - blog.qmd
      - proyects.qmd
      - certific.qmd
      - contacto.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/jxbsjb
      - icon: envelope
        href: mailto:joelburbano@outlook.com
  search:
    location: navbar
    type: textbox
format:
  html:
    #max-width: fit content(25em)
    code-fold: true
    code-tools: true
    code-block-bg: true
    code-block-border-left: "#0D2B71"
    theme:
      light: flatly
      dark: darkly
      
      
    linestretch: 1.7
    css: styles.css
    
    
lang: es    

editor: visual



    
    
execute: 
  warning: false
  freeze: true


# include GA4 script

# includes:
#   in-header: |
#     <script async src="https://www.googletagmanager.com/gtag/js?id=G-C1J6R1KB4G"></script>
#     <script>
#       window.dataLayer = window.dataLayer || [];
#       function gtag(){dataLayer.push(arguments);}
#       gtag('js', new Date());
# 
#       gtag('config', 'G-C1J6R1KB4G');
#     </script>
